[18/May/2017 09:26:30] DEBUG [django.db.backends:91] (0.006) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 09:26:30] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 09:26:48] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 09:26:48] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[18/May/2017 09:26:49] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[18/May/2017 09:26:49] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[18/May/2017 09:26:49] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[18/May/2017 09:26:49] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 09:26:49] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 09:26:49] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 09:26:49] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 09:26:49] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 09:26:49] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 09:26:49] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 09:26:49] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 09:26:49] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 09:26:49] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 09:26:51] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 200 2271
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 200 859
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 200 267194
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 200 61317
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 200 3121
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 200 141934
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 200 520714
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 200 15196
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 37045
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 116
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/js/home.js HTTP/1.1" 200 364
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 200 6949
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 200 2522
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 200 1833
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 200 2330
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 200 3518
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 200 5127
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 200 1587
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 200 3992
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 200 2347
[18/May/2017 09:26:51] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 200 36924
[18/May/2017 09:26:53] DEBUG [teledm.views:187] Debug message!
[18/May/2017 09:26:53] INFO [teledm.views:188] Info message!
[18/May/2017 09:26:53] WARNING [teledm.views:189] Warning message!
[18/May/2017 09:26:53] ERROR [teledm.views:190] Error message!
[18/May/2017 09:26:53] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 09:26:53] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 09:26:54] INFO [django.server:124] "GET /static/teledm/css/mapViewer.css HTTP/1.1" 200 921
[18/May/2017 09:26:54] INFO [django.server:124] "GET /static/highcharts-export-csv/export-csv.js HTTP/1.1" 200 11927
[18/May/2017 09:26:54] INFO [django.server:124] "GET /static/teledm/js/mapViewer.js HTTP/1.1" 200 62137
[18/May/2017 09:26:54] INFO [django.server:124] "GET /static/respond/src/respond.js HTTP/1.1" 200 9754
[18/May/2017 09:26:54] INFO [django.server:124] "GET /static/html5shiv/dist/html5shiv-printshiv.js HTTP/1.1" 200 16268
[18/May/2017 09:26:54] INFO [django.server:124] "GET /static/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[18/May/2017 09:26:54] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 09:26:55] INFO [django.server:124] "GET /static/teledm/images/info.png HTTP/1.1" 200 1010
[18/May/2017 09:26:55] INFO [django.server:124] "GET /static/teledm/images/pan.png HTTP/1.1" 200 606
[18/May/2017 09:26:55] INFO [django.server:124] "GET /static/teledm/images/zoomIn.png HTTP/1.1" 200 975
[18/May/2017 09:26:55] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 200 285
[18/May/2017 09:27:08] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 16038
[18/May/2017 09:27:08] INFO [django.server:124] "GET /static/teledm/js/mapDistForm.js HTTP/1.1" 200 22757
[18/May/2017 09:27:08] INFO [django.server:124] "GET /static/teledm/js/distPlot.js HTTP/1.1" 200 17791
[18/May/2017 09:27:09] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 09:27:09] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 09:27:09] WARNING [django.request:152] Not Found: /climdata.u-bourgogne.fr/teledm/CatalogTELEDM.xml
[18/May/2017 09:27:09] WARNING [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/CatalogTELEDM.xml HTTP/1.1" 404 7158
[18/May/2017 09:30:45] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 200 17407
[18/May/2017 09:30:45] INFO [django.server:124] "GET /static/highcharts-regression/highcharts-regression.js HTTP/1.1" 200 18756
[18/May/2017 09:30:45] INFO [django.server:124] "GET /static/teledm/js/calvalForm.js HTTP/1.1" 200 34586
[18/May/2017 09:30:45] INFO [django.server:124] "GET /static/teledm/js/localisation.js HTTP/1.1" 200 267
[18/May/2017 09:30:46] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 09:30:46] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 09:30:46] WARNING [django.request:152] Not Found: /climdata.u-bourgogne.fr/teledm/CatalogTELEDM.xml
[18/May/2017 09:30:46] WARNING [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/CatalogTELEDM.xml HTTP/1.1" 404 7158
[18/May/2017 09:30:48] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 16038
[18/May/2017 09:30:49] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 09:30:49] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 09:30:49] WARNING [django.request:152] Not Found: /climdata.u-bourgogne.fr/teledm/CatalogTELEDM.xml
[18/May/2017 09:30:49] WARNING [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/CatalogTELEDM.xml HTTP/1.1" 404 7158
[18/May/2017 09:31:13] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 09:31:13] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[18/May/2017 09:31:13] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[18/May/2017 09:31:13] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[18/May/2017 09:31:13] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[18/May/2017 09:31:13] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 09:31:13] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 09:31:13] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 09:31:13] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 09:31:13] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 09:31:13] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 09:31:13] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 09:31:13] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 09:31:13] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 09:31:13] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 09:31:15] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 200 2271
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 200 15196
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 200 859
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 200 3121
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 200 267194
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 116
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 200 141934
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 200 61317
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 37045
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/js/home.js HTTP/1.1" 200 364
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 200 520714
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 200 6949
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 200 36924
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 200 2330
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 200 2522
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 200 1833
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 200 5127
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 200 3518
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 200 2347
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 200 1587
[18/May/2017 09:31:15] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 200 3992
[18/May/2017 09:31:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 16038
[18/May/2017 09:31:18] INFO [django.server:124] "GET /static/teledm/js/distPlot.js HTTP/1.1" 200 17791
[18/May/2017 09:31:18] INFO [django.server:124] "GET /static/teledm/js/mapDistForm.js HTTP/1.1" 200 22804
[18/May/2017 09:31:18] INFO [django.server:124] "GET /static/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[18/May/2017 09:31:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 09:31:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/catalog.xml HTTP/1.1" 200 1285
[18/May/2017 09:31:27] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/catalog.xml HTTP/1.1" 200 1205
[18/May/2017 09:31:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/MYD07/catalog.xml HTTP/1.1" 200 1353
[18/May/2017 09:31:31] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/MYD07/res009/catalog.xml HTTP/1.1" 200 2232
[18/May/2017 09:31:34] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/dates/wms/satellite/modis/MYD07/res009/MYD07_r009_w.nc?service=WMS&version=1.3.0&request=GetCapabilities HTTP/1.1" 200 320902
[18/May/2017 09:32:23] INFO [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 179007
[18/May/2017 09:32:23] INFO [django.server:124] "GET /static/teledm/shapes/burkina_district_sante.geojson HTTP/1.1" 200 2497928
[18/May/2017 09:32:54] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/stationsAeronetTeom/ HTTP/1.1" 200 102
[18/May/2017 09:32:54] INFO [django.server:124] "GET /static/teledm/images/stations.png HTTP/1.1" 200 106286
[18/May/2017 09:32:54] INFO [django.server:124] "GET /static/teledm/images/listeStations.png HTTP/1.1" 200 37627
[18/May/2017 09:33:54] INFO [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 4233021
[18/May/2017 09:40:44] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 16038
[18/May/2017 09:40:45] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 09:41:08] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 16038
[18/May/2017 09:41:09] INFO [django.server:124] "GET /static/teledm/js/mapDistForm.js HTTP/1.1" 304 0
[18/May/2017 09:41:09] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 09:41:16] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/catalog.xml HTTP/1.1" 200 1285
[18/May/2017 09:41:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/toms/catalog.xml HTTP/1.1" 200 1125
[18/May/2017 09:41:22] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/toms/res125/catalog.xml HTTP/1.1" 200 13255
[18/May/2017 10:27:15] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:27:15] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:29:54] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:29:54] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:29:57] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 10:29:59] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/mapViewer/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: mapViewer() takes exactly 2 arguments (1 given)
[18/May/2017 10:29:59] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 500 89413
[18/May/2017 10:30:25] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:30:25] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:31:15] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:31:15] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:32:05] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:32:05] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:33:15] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:33:15] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:33:23] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 10:33:24] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 10:33:26] DEBUG [teledm.views:183] Debug message!
[18/May/2017 10:33:26] INFO [teledm.views:184] Info message!
[18/May/2017 10:33:26] WARNING [teledm.views:185] Warning message!
[18/May/2017 10:33:26] ERROR [teledm.views:186] Error message!
[18/May/2017 10:33:26] CRITICAL [teledm.views:187] Critical message!
[18/May/2017 10:33:26] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 10:33:27] INFO [django.server:124] "GET /static/html5shiv/dist/html5shiv-printshiv.js HTTP/1.1" 200 16268
[18/May/2017 10:33:27] INFO [django.server:124] "GET /static/teledm/css/mapViewer.css HTTP/1.1" 200 921
[18/May/2017 10:33:27] INFO [django.server:124] "GET /static/respond/src/respond.js HTTP/1.1" 200 9754
[18/May/2017 10:33:27] INFO [django.server:124] "GET /static/highcharts-export-csv/export-csv.js HTTP/1.1" 200 11927
[18/May/2017 10:33:27] INFO [django.server:124] "GET /static/teledm/js/mapViewer.js HTTP/1.1" 200 62137
[18/May/2017 10:33:27] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 10:33:28] INFO [django.server:124] "GET /static/teledm/images/pan.png HTTP/1.1" 200 606
[18/May/2017 10:33:28] INFO [django.server:124] "GET /static/teledm/images/info.png HTTP/1.1" 200 1010
[18/May/2017 10:33:28] INFO [django.server:124] "GET /static/teledm/images/zoomIn.png HTTP/1.1" 200 975
[18/May/2017 10:33:28] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 200 285
[18/May/2017 10:33:47] DEBUG [teledm.views:151] Debug message!
[18/May/2017 10:33:47] INFO [teledm.views:152] Info message!
[18/May/2017 10:33:47] WARNING [teledm.views:153] Warning message!
[18/May/2017 10:33:47] ERROR [teledm.views:154] Error message!
[18/May/2017 10:33:47] CRITICAL [teledm.views:155] Critical message!
[18/May/2017 10:33:47] INFO [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 286778
[18/May/2017 10:38:41] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:38:41] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:39:41] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:39:41] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:40:22] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:40:22] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:42:12] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:42:12] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:43:25] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:43:25] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:45:57] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:45:57] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:46:08] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:46:08] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:46:19] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:46:19] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:47:17] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:47:17] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:47:43] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:47:43] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:49:29] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 10:49:29] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 10:50:15] DEBUG [teledm.views:187] Debug message!
[18/May/2017 10:50:15] INFO [teledm.views:188] Info message!
[18/May/2017 10:50:15] WARNING [teledm.views:189] Warning message!
[18/May/2017 10:50:15] ERROR [teledm.views:190] Error message!
[18/May/2017 10:50:15] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 10:50:15] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 10:50:16] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 10:50:16] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 200 285
[18/May/2017 10:50:37] DEBUG [teledm.views:151] Debug message!
[18/May/2017 10:50:37] INFO [teledm.views:152] Info message!
[18/May/2017 10:50:37] WARNING [teledm.views:153] Warning message!
[18/May/2017 10:50:37] ERROR [teledm.views:154] Error message!
[18/May/2017 10:50:37] CRITICAL [teledm.views:155] Critical message!
[18/May/2017 10:50:37] INFO [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 286778
[18/May/2017 10:50:51] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 200 17407
[18/May/2017 10:50:51] INFO [django.server:124] "GET /static/highcharts-regression/highcharts-regression.js HTTP/1.1" 200 18756
[18/May/2017 10:50:51] INFO [django.server:124] "GET /static/teledm/js/calvalForm.js HTTP/1.1" 200 34639
[18/May/2017 10:50:51] INFO [django.server:124] "GET /static/teledm/js/localisation.js HTTP/1.1" 200 267
[18/May/2017 10:50:52] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 10:50:53] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 16038
[18/May/2017 10:50:54] INFO [django.server:124] "GET /static/teledm/js/mapDistForm.js HTTP/1.1" 304 0
[18/May/2017 10:50:54] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 10:51:09] INFO [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 197795
[18/May/2017 10:51:25] INFO [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 19773
[18/May/2017 11:01:07] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 11:01:07] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 11:01:56] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 11:01:56] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 11:02:34] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 11:02:34] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 12:21:25] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/mapDist/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 232, in mapDist
    df = pd.read_csv(fcsv, parse_dates={'datetime':['date']}, header=0, index_col=0, usecols=['date', variable])
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)
IOError: File /home/mers/Bureau/teledm/donnees/in_situ/meteo/Dedougou_meteo_3h.csv does not exist
[18/May/2017 12:21:25] ERROR [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 500 25803
[18/May/2017 12:46:25] INFO [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 1630292
[18/May/2017 13:03:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 13:03:25] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[18/May/2017 13:03:25] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[18/May/2017 13:03:25] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[18/May/2017 13:03:25] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[18/May/2017 13:03:25] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 13:03:25] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 13:03:25] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 13:03:25] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 13:03:25] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 13:03:25] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 13:03:25] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 13:03:25] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 13:03:25] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 13:03:25] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 13:03:26] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 200 2271
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 200 859
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 200 15196
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 200 267194
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 200 3121
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 200 520714
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 200 61317
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 37045
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 200 141934
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 5085
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/js/home.js HTTP/1.1" 200 364
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 200 6949
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 200 36924
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 200 2522
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 200 2330
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 200 1833
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 200 3518
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 200 5127
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 200 3992
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 200 1587
[18/May/2017 13:03:27] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 200 2347
[18/May/2017 13:03:29] DEBUG [teledm.views:186] Debug message!
[18/May/2017 13:03:29] INFO [teledm.views:187] Info message!
[18/May/2017 13:03:29] WARNING [teledm.views:188] Warning message!
[18/May/2017 13:03:29] ERROR [teledm.views:189] Error message!
[18/May/2017 13:03:29] CRITICAL [teledm.views:190] Critical message!
[18/May/2017 13:03:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 13:03:29] INFO [django.server:124] "GET /static/teledm/css/mapViewer.css HTTP/1.1" 200 921
[18/May/2017 13:03:29] INFO [django.server:124] "GET /static/highcharts-export-csv/export-csv.js HTTP/1.1" 200 11927
[18/May/2017 13:03:29] INFO [django.server:124] "GET /static/respond/src/respond.js HTTP/1.1" 200 9754
[18/May/2017 13:03:29] INFO [django.server:124] "GET /static/html5shiv/dist/html5shiv-printshiv.js HTTP/1.1" 200 16268
[18/May/2017 13:03:29] INFO [django.server:124] "GET /static/teledm/js/mapViewer.js HTTP/1.1" 200 57157
[18/May/2017 13:03:29] INFO [django.server:124] "GET /static/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[18/May/2017 13:03:30] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 13:03:30] INFO [django.server:124] "GET /static/teledm/images/info.png HTTP/1.1" 200 1010
[18/May/2017 13:03:30] INFO [django.server:124] "GET /static/teledm/images/pan.png HTTP/1.1" 200 606
[18/May/2017 13:03:30] INFO [django.server:124] "GET /static/teledm/images/zoomIn.png HTTP/1.1" 200 975
[18/May/2017 13:03:30] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 200 285
[18/May/2017 13:03:45] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapDist/ HTTP/1.1" 200 16038
[18/May/2017 13:03:46] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 304 0
[18/May/2017 13:03:46] INFO [django.server:124] "GET /static/teledm/js/mapDistForm.js HTTP/1.1" 200 22792
[18/May/2017 13:03:46] INFO [django.server:124] "GET /static/teledm/js/distPlot.js HTTP/1.1" 200 17791
[18/May/2017 13:03:46] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 13:07:44] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 13:07:44] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[18/May/2017 13:07:44] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[18/May/2017 13:07:44] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[18/May/2017 13:07:44] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[18/May/2017 13:07:44] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 13:07:44] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 13:07:44] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 13:07:44] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 13:07:44] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 13:07:44] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 13:07:44] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 13:07:44] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 13:07:44] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 13:07:44] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 13:07:45] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 200 859
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 200 15196
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 200 2271
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 200 267194
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 200 141934
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 200 3121
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 200 61317
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 5085
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 37045
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 200 520714
[18/May/2017 13:07:45] INFO [django.server:124] "GET /static/teledm/js/home.js HTTP/1.1" 200 364
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 200 6949
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 200 2330
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 200 2522
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 200 36924
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 200 3518
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 200 1833
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 200 5127
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 200 2347
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 200 1587
[18/May/2017 13:07:46] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 200 3992
[18/May/2017 13:07:49] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 200 17407
[18/May/2017 13:07:49] INFO [django.server:124] "GET /static/highcharts-regression/highcharts-regression.js HTTP/1.1" 200 18756
[18/May/2017 13:07:49] INFO [django.server:124] "GET /static/teledm/js/localisation.js HTTP/1.1" 200 267
[18/May/2017 13:07:49] INFO [django.server:124] "GET /static/teledm/js/calvalForm.js HTTP/1.1" 200 34641
[18/May/2017 13:07:49] INFO [django.server:124] "GET /static/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[18/May/2017 13:07:49] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 13:10:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 13:10:18] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[18/May/2017 13:10:18] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[18/May/2017 13:10:18] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[18/May/2017 13:10:18] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[18/May/2017 13:10:18] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 13:10:18] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 13:10:18] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 13:10:18] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 13:10:18] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 13:10:18] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 13:10:18] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 13:10:18] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 13:10:18] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 13:10:18] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 13:10:20] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 200 859
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 200 15196
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 200 2271
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 200 3121
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 200 267194
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 5085
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 200 61317
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 37045
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 200 141934
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 200 520714
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/js/home.js HTTP/1.1" 200 364
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 200 36924
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 200 6949
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 200 2522
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 200 1833
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 200 2330
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 200 3518
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 200 5127
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 200 1587
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 200 3992
[18/May/2017 13:10:20] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 200 2347
[18/May/2017 13:10:22] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 200 17407
[18/May/2017 13:10:22] INFO [django.server:124] "GET /static/highcharts-regression/highcharts-regression.js HTTP/1.1" 200 18756
[18/May/2017 13:10:22] INFO [django.server:124] "GET /static/teledm/js/localisation.js HTTP/1.1" 200 267
[18/May/2017 13:10:22] INFO [django.server:124] "GET /static/teledm/js/calvalForm.js HTTP/1.1" 200 29673
[18/May/2017 13:10:23] INFO [django.server:124] "GET /static/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[18/May/2017 13:10:23] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 13:12:41] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 200 17407
[18/May/2017 13:12:42] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 304 0
[18/May/2017 13:12:42] INFO [django.server:124] "GET /static/teledm/js/calvalForm.js HTTP/1.1" 304 0
[18/May/2017 13:12:42] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 13:33:00] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 13:33:01] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[18/May/2017 13:33:01] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[18/May/2017 13:33:01] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[18/May/2017 13:33:01] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[18/May/2017 13:33:01] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 13:33:01] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 13:33:01] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 13:33:01] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 13:33:01] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 13:33:01] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[18/May/2017 13:33:01] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[18/May/2017 13:33:01] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[18/May/2017 13:33:01] WARNING [django.request:152] Not Found: /favicon.ico
[18/May/2017 13:33:01] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[18/May/2017 13:33:02] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 200 859
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 200 2271
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 200 15196
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 200 267194
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 200 520714
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 200 3121
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 9369
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/js/home.js HTTP/1.1" 200 364
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 37045
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 200 61317
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 200 141934
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 200 36924
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 200 6949
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 200 2522
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 200 2330
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 200 1833
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 200 3518
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 200 1587
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 200 2347
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 200 5127
[18/May/2017 13:33:03] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 200 3992
[18/May/2017 13:33:05] DEBUG [teledm.views:186] Debug message!
[18/May/2017 13:33:05] INFO [teledm.views:187] Info message!
[18/May/2017 13:33:05] WARNING [teledm.views:188] Warning message!
[18/May/2017 13:33:05] ERROR [teledm.views:189] Error message!
[18/May/2017 13:33:05] CRITICAL [teledm.views:190] Critical message!
[18/May/2017 13:33:05] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 13:33:05] INFO [django.server:124] "GET /static/teledm/css/mapViewer.css HTTP/1.1" 200 921
[18/May/2017 13:33:05] INFO [django.server:124] "GET /static/highcharts-export-csv/export-csv.js HTTP/1.1" 200 11927
[18/May/2017 13:33:05] INFO [django.server:124] "GET /static/teledm/js/mapViewer.js HTTP/1.1" 200 53722
[18/May/2017 13:33:05] INFO [django.server:124] "GET /static/respond/src/respond.js HTTP/1.1" 200 9754
[18/May/2017 13:33:05] INFO [django.server:124] "GET /static/html5shiv/dist/html5shiv-printshiv.js HTTP/1.1" 200 16268
[18/May/2017 13:33:05] INFO [django.server:124] "GET /static/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[18/May/2017 13:33:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 13:33:06] INFO [django.server:124] "GET /static/teledm/images/pan.png HTTP/1.1" 200 606
[18/May/2017 13:33:06] INFO [django.server:124] "GET /static/teledm/images/zoomIn.png HTTP/1.1" 200 975
[18/May/2017 13:33:06] INFO [django.server:124] "GET /static/teledm/images/info.png HTTP/1.1" 200 1010
[18/May/2017 13:33:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 200 285
[18/May/2017 13:33:10] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/catalog.xml HTTP/1.1" 200 1285
[18/May/2017 13:33:13] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/catalog.xml HTTP/1.1" 200 1205
[18/May/2017 13:33:15] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/MYD07/catalog.xml HTTP/1.1" 200 1353
[18/May/2017 13:33:16] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/MYD07/res009/catalog.xml HTTP/1.1" 200 2232
[18/May/2017 13:33:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/dates/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetCapabilities HTTP/1.1" 200 422993
[18/May/2017 13:33:23] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/minmax/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?item=minmax&LAYERS=Surface_Temperature&elevation=Layer&TIME=2002-07-12&SRS=EPSG%3A4326&CRS=EPSG%3A4326&REQUEST=GetMetadata&service=WMS&version=1.3.0&BBOX=-27,-0.5,58,52&WIDTH=50&HEIGHT=50 HTTP/1.1" 200 32
[18/May/2017 13:33:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-50%2C50&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=24.8,-90,127.2,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 779
[18/May/2017 13:33:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-50%2C50&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=-77.6,12.4,24.8,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1528
[18/May/2017 13:33:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-50%2C50&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=-180,-90,-77.6,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 205
[18/May/2017 13:33:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-50%2C50&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=-180,12.4,-77.6,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 205
[18/May/2017 13:33:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-50%2C50&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=-77.6,-90,24.8,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 748
[18/May/2017 13:33:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-50%2C50&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=24.8,12.4,127.2,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1446
[18/May/2017 13:33:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-50%2C50&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=127.2,-90,229.6,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 205
[18/May/2017 13:33:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-50%2C50&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=127.2,12.4,229.6,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 205
[18/May/2017 13:33:27] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/minmax/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?item=minmax&LAYERS=Surface_Temperature&elevation=Layer&TIME=2002-07-12&SRS=EPSG%3A4326&CRS=EPSG%3A4326&REQUEST=GetMetadata&service=WMS&version=1.3.0&BBOX=-27,-0.5,58,52&WIDTH=50&HEIGHT=50 HTTP/1.1" 200 32
[18/May/2017 13:33:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=-77.6,12.4,24.8,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 3567
[18/May/2017 13:33:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=-180,12.4,-77.6,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 205
[18/May/2017 13:33:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=-77.6,-90,24.8,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1043
[18/May/2017 13:33:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=24.8,-90,127.2,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1219
[18/May/2017 13:33:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=-180,-90,-77.6,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 205
[18/May/2017 13:33:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=24.8,12.4,127.2,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 3314
[18/May/2017 13:33:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=127.2,-90,229.6,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 205
[18/May/2017 13:33:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=10&OPACITY=100&BBOX=127.2,12.4,229.6,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 205
[18/May/2017 13:33:32] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=100&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 200 627
[18/May/2017 13:33:33] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/minmax/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?item=minmax&LAYERS=Surface_Temperature&elevation=Layer&TIME=2002-07-12&SRS=EPSG%3A4326&CRS=EPSG%3A4326&REQUEST=GetMetadata&service=WMS&version=1.3.0&BBOX=-27,-0.5,58,52&WIDTH=50&HEIGHT=50 HTTP/1.1" 200 32
[18/May/2017 13:33:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-77.6,-90,24.8,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1762
[18/May/2017 13:33:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=24.8,12.4,127.2,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 6020
[18/May/2017 13:33:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=24.8,-90,127.2,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 2088
[18/May/2017 13:33:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-180,12.4,-77.6,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:33:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-180,-90,-77.6,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:33:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-77.6,12.4,24.8,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 6967
[18/May/2017 13:33:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=127.2,-90,229.6,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:33:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=127.2,12.4,229.6,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.4257743898705,12.534175914429,15.747063109364,21.855464633922&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 6525
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.4257743898705,21.855464633922,15.747063109364,31.176753353416&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 8052
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.4257743898705,3.2128871949353,15.747063109364,12.534175914429&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 4625
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=15.747063109364,21.855464633922,25.068351828858,31.176753353416&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 7537
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-2.895514329623,12.534175914429,6.4257743898705,21.855464633922&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 8916
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=15.747063109364,12.534175914429,25.068351828858,21.855464633922&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 8597
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-2.895514329623,21.855464633922,6.4257743898705,31.176753353416&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 10030
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=15.747063109364,3.2128871949353,25.068351828858,12.534175914429&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 7993
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.4257743898705,31.176753353416,15.747063109364,40.498042072909&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 7092
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=25.068351828858,12.534175914429,34.389640548351,21.855464633922&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 5806
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=15.747063109364,31.176753353416,25.068351828858,40.498042072909&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 6839
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=25.068351828858,21.855464633922,34.389640548351,31.176753353416&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 7615
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-2.895514329623,3.2128871949353,6.4257743898705,12.534175914429&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 5755
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-2.895514329623,31.176753353416,6.4257743898705,40.498042072909&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 7635
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=25.068351828858,3.2128871949353,34.389640548351,12.534175914429&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 5712
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=34.389640548351,12.534175914429,43.710929267845,21.855464633922&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 4314
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=25.068351828858,31.176753353416,34.389640548351,40.498042072909&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 6433
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=34.389640548351,21.855464633922,43.710929267845,31.176753353416&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 8485
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=34.389640548351,3.2128871949353,43.710929267845,12.534175914429&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 5374
[18/May/2017 13:33:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=34.389640548351,31.176753353416,43.710929267845,40.498042072909&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 10084
[18/May/2017 13:33:51] INFO [django.server:124] "GET /static/teledm/shapes//stations.geojson HTTP/1.1" 200 8099
[18/May/2017 13:34:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-12.216803049117,-6.1084015245583,-2.895514329623,3.2128871949353&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1381
[18/May/2017 13:34:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-12.216803049117,21.855464633922,-2.895514329623,31.176753353416&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 9655
[18/May/2017 13:34:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-12.216803049117,12.534175914429,-2.895514329623,21.855464633922&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 6413
[18/May/2017 13:34:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-12.216803049117,3.2128871949353,-2.895514329623,12.534175914429&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 2368
[18/May/2017 13:34:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-2.895514329623,-6.1084015245583,6.4257743898705,3.2128871949353&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1741
[18/May/2017 13:34:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.4257743898705,-6.1084015245583,15.747063109364,3.2128871949353&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1326
[18/May/2017 13:34:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=15.747063109364,-6.1084015245583,25.068351828858,3.2128871949353&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 2881
[18/May/2017 13:34:18] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=25.068351828858,-6.1084015245583,34.389640548351,3.2128871949353&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 3185
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.491826187925,-7.1147439164778,27.213140208806,13.606570104403&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 13040
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=27.213140208806,-7.1147439164778,47.934454229686,13.606570104403&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 14291
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.491826187925,13.606570104403,27.213140208806,34.327884125283&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 25887
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=27.213140208806,13.606570104403,47.934454229686,34.327884125283&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 25719
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-14.229487832956,13.606570104403,6.491826187925,34.327884125283&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 29200
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.491826187925,34.327884125283,27.213140208806,55.049198146164&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 23631
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-14.229487832956,-7.1147439164778,6.491826187925,13.606570104403&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 8612
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=6.491826187925,-27.836057937358,27.213140208806,-7.1147439164778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=27.213140208806,34.327884125283,47.934454229686,55.049198146164&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 25481
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-14.229487832956,34.327884125283,6.491826187925,55.049198146164&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 17038
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=27.213140208806,-27.836057937358,47.934454229686,-7.1147439164778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=47.934454229686,13.606570104403,68.655768250567,34.327884125283&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 13670
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=47.934454229686,-7.1147439164778,68.655768250567,13.606570104403&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 6397
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-14.229487832956,-27.836057937358,6.491826187925,-7.1147439164778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=47.934454229686,34.327884125283,68.655768250567,55.049198146164&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 10006
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=47.934454229686,-27.836057937358,68.655768250567,-7.1147439164778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=68.655768250567,13.606570104403,89.377082271447,34.327884125283&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=68.655768250567,-7.1147439164778,89.377082271447,13.606570104403&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=68.655768250567,34.327884125283,89.377082271447,55.049198146164&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:19] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=68.655768250567,-27.836057937358,89.377082271447,-7.1147439164778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=36.264879901779,2.6849485293337,67.15986274489,33.579931372445&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 22296
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=36.264879901779,33.579931372445,67.15986274489,64.474914215556&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 15096
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=5.3698970586674,33.579931372445,36.264879901779,64.474914215556&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 20194
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-25.525085784444,2.6849485293337,5.3698970586674,33.579931372445&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 18969
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=5.3698970586674,-28.210034313778,36.264879901779,2.6849485293337&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 2857
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=5.3698970586674,2.6849485293337,36.264879901779,33.579931372445&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 28757
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=36.264879901779,-28.210034313778,67.15986274489,2.6849485293337&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 2019
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-25.525085784444,33.579931372445,5.3698970586674,64.474914215556&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 10957
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=67.15986274489,33.579931372445,98.054845588001,64.474914215556&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-25.525085784444,-28.210034313778,5.3698970586674,2.6849485293337&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 1386
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=67.15986274489,2.6849485293337,98.054845588001,33.579931372445&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=67.15986274489,-28.210034313778,98.054845588001,2.6849485293337&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=5.3698970586674,-59.105017156889,36.264879901779,-28.210034313778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=36.264879901779,-59.105017156889,67.15986274489,-28.210034313778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=98.054845588001,2.6849485293337,128.94982843111,33.579931372445&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=-25.525085784444,-59.105017156889,5.3698970586674,-28.210034313778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=67.15986274489,-59.105017156889,98.054845588001,-28.210034313778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=98.054845588001,33.579931372445,128.94982843111,64.474914215556&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=98.054845588001,-28.210034313778,128.94982843111,2.6849485293337&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:26] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=284.21%2C343.31&TIME=2002-07-12&NUMCOLORBANDS=100&OPACITY=100&BBOX=98.054845588001,-59.105017156889,128.94982843111,-28.210034313778&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 475
[18/May/2017 13:34:45] DEBUG [teledm.views:150] Debug message!
[18/May/2017 13:34:45] INFO [teledm.views:151] Info message!
[18/May/2017 13:34:45] WARNING [teledm.views:152] Warning message!
[18/May/2017 13:34:45] ERROR [teledm.views:153] Error message!
[18/May/2017 13:34:45] CRITICAL [teledm.views:154] Critical message!
[18/May/2017 13:34:45] INFO [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20084
[18/May/2017 13:34:58] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 200 17407
[18/May/2017 13:34:58] INFO [django.server:124] "GET /static/highcharts-regression/highcharts-regression.js HTTP/1.1" 200 18756
[18/May/2017 13:34:58] INFO [django.server:124] "GET /static/teledm/js/calvalForm.js HTTP/1.1" 200 29213
[18/May/2017 13:34:58] INFO [django.server:124] "GET /static/teledm/js/localisation.js HTTP/1.1" 200 267
[18/May/2017 13:34:58] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 304 0
[18/May/2017 13:34:59] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 13:35:01] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/catalog.xml HTTP/1.1" 200 1285
[18/May/2017 13:35:03] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/catalog.xml HTTP/1.1" 200 1205
[18/May/2017 13:35:05] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/MYD07/catalog.xml HTTP/1.1" 200 1353
[18/May/2017 13:35:07] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/MYD07/res009/catalog.xml HTTP/1.1" 200 2232
[18/May/2017 13:35:08] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/dates/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetCapabilities HTTP/1.1" 200 422993
[18/May/2017 13:35:45] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/calval/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 322, in calval
    inSitu, station, varStation, niveau
  File "/home/mers/dev/crc/teledm/scatterPlots.py", line 217, in scatterSatStation
    hours1,long_st1, lat_st1 = heure_passage(station)
  File "/home/mers/dev/crc/teledm/scatterPlots.py", line 176, in heure_passage
    latst=np.asarray(coord_st[coord_st['nom'].isin([station_aeronet])].lat)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'nom'
[18/May/2017 13:35:45] ERROR [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 500 26333
[18/May/2017 13:35:56] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 200 17407
[18/May/2017 13:35:57] INFO [django.server:124] "GET /static/teledm/js/calvalForm.js HTTP/1.1" 304 0
[18/May/2017 13:35:57] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 304 0
[18/May/2017 13:35:57] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 1614
[18/May/2017 13:36:01] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/catalog.xml HTTP/1.1" 200 1285
[18/May/2017 13:36:03] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/catalog.xml HTTP/1.1" 200 1205
[18/May/2017 13:36:04] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/MYD07/catalog.xml HTTP/1.1" 200 1353
[18/May/2017 13:36:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalog/satellite/modis/MYD07/res009/catalog.xml HTTP/1.1" 200 2232
[18/May/2017 13:36:08] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/dates/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetCapabilities HTTP/1.1" 200 422993
[18/May/2017 13:36:32] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/calval/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 322, in calval
    inSitu, station, varStation, niveau
  File "/home/mers/dev/crc/teledm/scatterPlots.py", line 217, in scatterSatStation
    hours1,long_st1, lat_st1 = heure_passage(station)
  File "/home/mers/dev/crc/teledm/scatterPlots.py", line 176, in heure_passage
    latst=np.asarray(coord_st[coord_st['nom'].isin([station_aeronet])].lat)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/home/mers/.local/lib/python2.7/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'nom'
[18/May/2017 13:36:32] ERROR [django.server:124] "POST /climdata.u-bourgogne.fr/teledm/calval/ HTTP/1.1" 500 26333
[18/May/2017 14:07:24] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 14:07:24] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[18/May/2017 14:07:24] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[18/May/2017 14:07:24] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[18/May/2017 14:07:24] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[18/May/2017 18:23:43] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:23:43] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:23:48] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 18:23:50] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 18:23:50] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 9543
[18/May/2017 18:23:54] DEBUG [teledm.views:186] Debug message!
[18/May/2017 18:23:54] INFO [teledm.views:187] Info message!
[18/May/2017 18:23:54] WARNING [teledm.views:188] Warning message!
[18/May/2017 18:23:54] ERROR [teledm.views:189] Error message!
[18/May/2017 18:23:54] CRITICAL [teledm.views:190] Critical message!
[18/May/2017 18:23:54] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:23:55] INFO [django.server:124] "GET /static/teledm/js/mapViewer.js HTTP/1.1" 200 53721
[18/May/2017 18:23:55] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 62, in proxyAjax
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD))
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/catalogRefs/CatalogTELEDEM.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f23dc4b8350>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:23:55] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 500 26174
[18/May/2017 18:23:56] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 72, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f23de5182d0>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:23:56] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
[18/May/2017 18:26:22] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:26:22] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:26:25] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 18:26:29] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 18:26:33] DEBUG [teledm.views:186] Debug message!
[18/May/2017 18:26:33] INFO [teledm.views:187] Info message!
[18/May/2017 18:26:33] WARNING [teledm.views:188] Warning message!
[18/May/2017 18:26:33] ERROR [teledm.views:189] Error message!
[18/May/2017 18:26:33] CRITICAL [teledm.views:190] Critical message!
[18/May/2017 18:26:33] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:26:33] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 62, in proxyAjax
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD))
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/catalogRefs/CatalogTELEDEM.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f46e15e4c50>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:26:33] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 500 26174
[18/May/2017 18:26:34] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 72, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f46e1607790>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:26:34] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
[18/May/2017 18:26:59] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:26:59] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:27:02] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[18/May/2017 18:27:03] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8785
[18/May/2017 18:27:05] DEBUG [teledm.views:186] Debug message!
[18/May/2017 18:27:05] INFO [teledm.views:187] Info message!
[18/May/2017 18:27:05] WARNING [teledm.views:188] Warning message!
[18/May/2017 18:27:05] ERROR [teledm.views:189] Error message!
[18/May/2017 18:27:05] CRITICAL [teledm.views:190] Critical message!
[18/May/2017 18:27:05] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:27:06] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 62, in proxyAjax
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD))
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/catalogRefs/CatalogTELEDEM.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efc2db4fc50>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:27:06] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 500 26174
[18/May/2017 18:27:06] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 72, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efc2db72790>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:27:06] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127181
[18/May/2017 18:27:32] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:27:32] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:27:38] DEBUG [teledm.views:187] Debug message!
[18/May/2017 18:27:38] INFO [teledm.views:188] Info message!
[18/May/2017 18:27:38] WARNING [teledm.views:189] Warning message!
[18/May/2017 18:27:38] ERROR [teledm.views:190] Error message!
[18/May/2017 18:27:38] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 18:27:38] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:27:39] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 63, in proxyAjax
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD))
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/catalogRefs/CatalogTELEDEM.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6d0c49e310>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:27:39] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 500 26174
[18/May/2017 18:27:39] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 73, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6d0c449490>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:27:39] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
[18/May/2017 18:32:29] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:32:29] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:33:24] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:33:24] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:33:55] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:33:55] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:34:06] DEBUG [teledm.views:187] Debug message!
[18/May/2017 18:34:06] INFO [teledm.views:188] Info message!
[18/May/2017 18:34:06] WARNING [teledm.views:189] Warning message!
[18/May/2017 18:34:06] ERROR [teledm.views:190] Error message!
[18/May/2017 18:34:06] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 18:34:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:34:07] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 200 20
[18/May/2017 18:34:07] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 73, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fde1ed31e90>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:34:07] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127181
[18/May/2017 18:38:20] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:38:20] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:38:42] DEBUG [teledm.views:187] Debug message!
[18/May/2017 18:38:42] INFO [teledm.views:188] Info message!
[18/May/2017 18:38:42] WARNING [teledm.views:189] Warning message!
[18/May/2017 18:38:42] ERROR [teledm.views:190] Error message!
[18/May/2017 18:38:42] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 18:38:42] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:38:43] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 65, in proxyAjax
    return render('teledm/ErrrorConn.html', {'exception': 'Connexion Impossible'}, context_instance=RequestContext(request), status=404)
TypeError: render() got an unexpected keyword argument 'context_instance'
[18/May/2017 18:38:43] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 500 24965
[18/May/2017 18:38:43] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 73, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fef5d7eae50>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:38:43] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
[18/May/2017 18:39:06] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:39:06] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:39:14] DEBUG [teledm.views:187] Debug message!
[18/May/2017 18:39:14] INFO [teledm.views:188] Info message!
[18/May/2017 18:39:14] WARNING [teledm.views:189] Warning message!
[18/May/2017 18:39:14] ERROR [teledm.views:190] Error message!
[18/May/2017 18:39:14] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 18:39:14] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:39:15] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 65, in proxyAjax
    return render('teledm/ErrrorConn.html', {'exception': 'Connexion Impossible'}, status=404)
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: {'exception': 'Connexion Impossible'}
[18/May/2017 18:39:15] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 500 26025
[18/May/2017 18:39:15] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 73, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7edece7510>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:39:15] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
[18/May/2017 18:41:56] DEBUG [teledm.views:187] Debug message!
[18/May/2017 18:41:56] INFO [teledm.views:188] Info message!
[18/May/2017 18:41:56] WARNING [teledm.views:189] Warning message!
[18/May/2017 18:41:56] ERROR [teledm.views:190] Error message!
[18/May/2017 18:41:56] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 18:41:56] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:41:57] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 65, in proxyAjax
    return render('teledm/ErrrorConn.html', {'exception': 'Connexion Impossible'}, status=404)
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: {'exception': 'Connexion Impossible'}
[18/May/2017 18:41:57] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 500 26025
[18/May/2017 18:41:57] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 73, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7edece7050>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:41:57] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
[18/May/2017 18:48:29] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:48:29] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:48:33] DEBUG [teledm.views:187] Debug message!
[18/May/2017 18:48:33] INFO [teledm.views:188] Info message!
[18/May/2017 18:48:33] WARNING [teledm.views:189] Warning message!
[18/May/2017 18:48:33] ERROR [teledm.views:190] Error message!
[18/May/2017 18:48:33] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 18:48:33] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:48:34] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 65, in proxyAjax
    return render('teledm/ErrrorConnexion.html', {'exception': 'Connexion Impossible'}, status=404)
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: {'exception': 'Connexion Impossible'}
[18/May/2017 18:48:34] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 500 26030
[18/May/2017 18:48:34] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 73, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4b08efe4d0>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:48:34] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
[18/May/2017 18:49:04] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:49:04] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:49:10] DEBUG [teledm.views:187] Debug message!
[18/May/2017 18:49:10] INFO [teledm.views:188] Info message!
[18/May/2017 18:49:10] WARNING [teledm.views:189] Warning message!
[18/May/2017 18:49:10] ERROR [teledm.views:190] Error message!
[18/May/2017 18:49:10] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 18:49:10] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:49:11] WARNING [django.request:152] Not Found: /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml
[18/May/2017 18:49:11] WARNING [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 404 27
[18/May/2017 18:49:11] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 73, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0c4e13be10>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:49:11] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
[18/May/2017 18:53:45] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[18/May/2017 18:53:45] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[18/May/2017 18:53:47] DEBUG [teledm.views:187] Debug message!
[18/May/2017 18:53:47] INFO [teledm.views:188] Info message!
[18/May/2017 18:53:47] WARNING [teledm.views:189] Warning message!
[18/May/2017 18:53:47] ERROR [teledm.views:190] Error message!
[18/May/2017 18:53:47] CRITICAL [teledm.views:191] Critical message!
[18/May/2017 18:53:47] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20375
[18/May/2017 18:53:48] INFO [django.server:124] "GET /static/teledm/js/mapViewer.js HTTP/1.1" 304 0
[18/May/2017 18:53:48] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 304 0
[18/May/2017 18:53:48] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxyajax/catalogRefs/CatalogTELEDEM.xml HTTP/1.1" 302 0
[18/May/2017 18:53:48] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 73, in colorbar
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='climdata.u-bourgogne.fr', port=8443): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd872241d90>: Failed to establish a new connection: [Errno 113] No route to host',))
[18/May/2017 18:53:49] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/colorbar/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?REQUEST=GetLegendGraphic&LAYER=Surface_Temperature&NUMCOLORBANDS=10&PALETTE=rainbow&COLORBARONLY=true HTTP/1.1" 500 127182
